dist: trusty
sudo: false

language: node_js

node_js:
  - "10"

branches:
  only:
    - master

notifications:
  email: false

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/smart-sales
  on:
    branch: master
